version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpwd
      - POSTGRES_DB=db
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mysql:
    image: mysql
    ports:
      - "3306:3306"