swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger Document Edition "
host: "loclhost:8080"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /documents:
    post:
      tags: 
        - documents
      summary: create a document
      parameters:
        - name: document
          in: body
          required: true
          schema:
            $ref: "#/definitions/document"
      responses:
        201:
          description: le document créé
          schema:
            $ref: '#/definitions/document'
        400:
          description: le contenu n'est pas correction
          schema:
            $ref: '#/definitions/errorDefinition'
    get:
      tags: 
        - documents
      summary: retourne tous les documents, pas de filtrage
      parameters: 
        - name: page
          type: integer
          in: query
          description: numéro de la page à retourner
        - name: pageSize
          type: integer
          in: query
          description: nombre de documents par page
      responses:
        200: 
          description: la liste des documents
          schema:
            $ref: '#/definitions/documentsList'
  /documents/{documentId}:
    parameters: 
      - name: documentId
        type: string
        in: path
        required: true
        description: identifiant du document
    get: 
      summary: lis le document
      tags: 
        - documents
      description: retourne un document
      responses: 
        200:
          description: le document demandé
          schema: 
            $ref: '#/definitions/document'
        404:
          description: le document n'existe pas
          schema:
            $ref: '#/definitions/errorDefinition'
    post:
      tags: 
        - documents
      summary: mise à jour du document
      description: |
        met à jour le document si l'utilisateur possède la dernière version et que personne n'a posé de verrou
      parameters:
        - name: document
          in: body
          schema:
            $ref: '#/definitions/document'
          description: met à jour le texte, le titre, l'editeur et la date de mise à jour
      responses:
        200:
          description: le document est mis à jour
          schema: 
            $ref: '#/definitions/document'
  /documents/{documentId}/lock:
    parameters: 
      - name: documentId
        type: string
        in: path
        required: true
        description: identifiant du document
    get:
      tags: 
        - locks
      summary: retourne le verrou posé sur le document si présent
      responses:
        200:
          description: le verrou posé
          schema:
            $ref: '#/definitions/lock'
        204:
          description: aucun verrou posé
    put:
      tags: 
        - locks
      summary: pose un verrou sur le document
      description: |
        l'utilisateur peut poser un verrou si aucun n'autre n'est posé
      parameters:
        - name: lock
          in: body
          description: l'objet verrou posé
          schema: 
            $ref: "#/definitions/lock"
      responses:
        200: 
          description: le verrou est posé
          schema:
            $ref: "#/definitions/lock"
        409: 
          description: un verrou est déjà posé, retourne le verrou déjà posé
          schema: 
            $ref: "#/definitions/lock"
    delete:
      tags: 
        - locks
      summary: supprime le verrou posé 
      responses:
        204:
          description: le verrou est supprimé
definitions:
  pageData:
    description: objet générique pour les résultats de recherche
    type: object
    properties:
      page: 
        type: integer
        description: le numéro de la page courante
      nbElements:
        description: le nombre total d'element
        type: integer
  documentSummary:
    description: résumé d'un document
    type: object
    properties:
      documentId:
        type: string
        description: identifiant du document
      created: 
        type: string
        format: date-time
        description: la date de création
      updated:
        type: string
        format: date-time
        description: date de la mise à jour
      title:
        type: string
        description: titre du document
  document: 
    description: a document
    allOf: 
      - $ref: "#/definitions/documentSummary"
    properties:
      creator: 
        type: string
        description: le nom du créateur du document
      editor:
        type: string
        description: le nom du dernier utilisateur qui l'a mis à jour
      body:
        type: string
        description: le texte du document
  documentsList:
    description: la liste des résultats d'une recherche de document
    allOf: 
      - $ref: '#/definitions/pageData'
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/documentSummary"
  lock:
    description: un verrou
    type: object
    properties:
      owner:
        type: string
        description: utilisateur propriétaire du verrou
      created: 
        description: date de la pose du verrou
        type: string
        format: date-time
  errorDefinition:
    description: la description de l'erreur
    type: object
    properties:
      errorType: 
        type: string
        description: le type d'erreur
        enum:
          - TECHNICAL
          - FUNCTIONAL
      errors:
        type: array
        items:
          type: object
          properties:
            errorCode: 
              type: string
              description: le code de l'erreur
            errorMessage:
              type: string
              description: message d'erreur